print("Họ và Tên của iem: ")
Ten = input()
print("Tuổi của iem: ")
Tuoi = input(int)
print("Giới tính: ")
GT = input()
print("Tình Trạng hôn nhân: ")
TT = input()
print("Họ và Tên của iem: " + Ten)
print("Tuổi của iem: " + Tuoi)
print("Giới tính: " + GT)
print("Tình Trạng hôn nhân: " + TT)